name: flutter_template_clean_architecture
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.0.1
  # Simplify Equality Comparisons
  equatable: ^2.0.3
  # Tools for programming in a functional style
  dartz: ^0.10.1
  # Service Locator
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

#flutter_native_splash:
#  background_image: assets/logo/background_white_splash_screen.png
#  image: assets/logo/logo_black_big.png
#  background_image_dark: assets/logo/background_black_splash_screen.png
#  image_dark: assets/logo/logo_white_big.png
#  android_12:
#    # color: "#ffffff"
#    image: assets/logo/android12_splash_black.png
#    # color_dark: "#3A3F45"
#    image_dark: assets/logo/android12_splash_white.png
  # flutter pub run flutter_native_splash:create